spring:
  application:
    name: location-service

#  db connection
  datasource:
    url: jdbc:postgresql://localhost:5432/ca_connect_db
    username: postgres
    password: ${DB_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# eureka client config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# port configuration
server:
  port: 8082